version: "3.9"

services:
  frontend:
    image: app.py
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - shared-data:/data
    depends_on:
      - backend

  backend:
    image: DataCleaner.py
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - shared-data:/data
    environment:
      - WATCH_INTERVAL=3

volumes:
  shared-data:
